version: '2'
services:
  datastore:
    image: busybox
    volumes:
      # - /share
      - ./docker/mysql/volumes:/var/lib/mysql

  # server:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   ports:
  #     - '80:80'
  #   volumes_from:
  #     - datastore
  #   depends_on:
  #     - datastore

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    # command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    depends_on:
      - datastore
    extends:
      file: ./docker/mysql/password.yml
      service: password
